export const COUNTRY_OBJCECT_REQUEST = "COUNTRY_OBJCECT_REQUEST";
export const COUNTRY_OBJCECT_SUCCESS = "COUNTRY_OBJCECT_SUCCESS";
export const COUNTRY_OBJCECT_FAIL = "COUNTRY_OBJCECT_FAIL";

export const COUNTRY_BY_ID_OBJCECT_REQUEST = "COUNTRY_BY_ID_OBJCECT_REQUEST";
export const COUNTRY_BY_ID_OBJCECT_SUCCESS = "COUNTRY_BY_ID_OBJCECT_SUCCESS";
export const COUNTRY_BY_ID_OBJCECT_FAIL = "COUNTRY_BY_ID_OBJCECT_FAIL";