export const OFFER_OBJCECT_REQUEST = "OFFER_OBJCECT_REQUEST";
export const OFFER_OBJCECT_SUCCESS = "OFFER_OBJCECT_SUCCESS";
export const OFFER_OBJCECT_FAIL = "OFFER_OBJCECT_FAIL";

export const OFFERTHEBEST_OBJCECT_REQUEST = "OFFERTHEBEST_OBJCECT_REQUEST";
export const OFFERTHEBEST_OBJCECT_SUCCESS = "OFFERTHEBEST_OBJCECT_SUCCESS";
export const OFFERTHEBEST_OBJCECT_FAIL = "OFFERTHEBEST_OBJCECT_FAIL";

export const OFFEROURCHOICE_OBJCECT_REQUEST = "OFFEROURCHOICE_OBJCECT_REQUEST";
export const OFFEROURCHOICE_OBJCECT_SUCCESS = "OFFEROURCHOICE_OBJCECT_SUCCESS";
export const OFFEROURCHOICE_OBJCECT_FAIL = "OFFEROURCHOICE_OBJCECT_FAIL";

export const OFFER_BY_ID_OBJCECT_REQUEST = "OFFER_BY_ID_OBJCECT_REQUEST";
export const OFFER_BY_ID_OBJCECT_SUCCESS = "OFFER_BY_ID_OBJCECT_SUCCESS";
export const OFFER_BY_ID_OBJCECT_FAIL = "OFFER_BY_ID_OBJCECT_FAIL";

