export const OPINIONS_BY_OFFER_OBJCECT_REQUEST = "OPINIONS_BY_OFFER_OBJCECT_REQUEST";
export const OPINIONS_BY_OFFER_OBJCECT_SUCCESS = "OPINIONS_BY_OFFER_OBJCECT_SUCCESS";
export const OPINIONS_BY_OFFER_OBJCECT_FAIL = "OPINIONS_BY_OFFER_OBJCECT_FAIL";

export const OPINIONS_BY_USER_OBJCECT_REQUEST = "OPINIONS_BY_USER_OBJCECT_REQUEST";
export const OPINIONS_BY_USER_OBJCECT_SUCCESS = "OPINIONS_BY_USER_OBJCECT_SUCCESS";
export const OPINIONS_BY_USER_OBJCECT_FAIL = "OPINIONS_BY_USER_OBJCECT_FAIL";