export const OPINIONS_BY_OFFER_OBJCECT_REQUEST = "OPINIONS_BY_OFFER_OBJCECT_REQUEST";
export const OPINIONS_BY_OFFER_OBJCECT_SUCCESS = "OPINIONS_BY_OFFER_OBJCECT_SUCCESS";
export const OPINIONS_BY_OFFER_OBJCECT_FAIL = "OPINIONS_BY_OFFER_OBJCECT_FAIL";

export const OPINIONS_BY_USER_OBJCECT_REQUEST = "OPINIONS_BY_USER_OBJCECT_REQUEST";
export const OPINIONS_BY_USER_OBJCECT_SUCCESS = "OPINIONS_BY_USER_OBJCECT_SUCCESS";
export const OPINIONS_BY_USER_OBJCECT_FAIL = "OPINIONS_BY_USER_OBJCECT_FAIL";

export const DELETE_BY_USER_OBJCECT_REQUEST = "DELETE_BY_USER_OBJCECT_REQUEST";
export const DELETE_BY_USER_OBJCECT_SUCCESS = "DELETE_BY_USER_OBJCECT_SUCCESS";
export const DELETE_BY_USER_OBJCECT_FAIL = "DELETE_BY_USER_OBJCECT_FAIL";

export const UPGRADE_BY_USER_OBJCECT_REQUEST = "UPGRADE_BY_USER_OBJCECT_REQUEST";
export const UPGRADE_BY_USER_OBJCECT_SUCCESS = "UPGRADE_BY_USER_OBJCECT_SUCCESS";
export const UPGRADE_BY_USER_OBJCECT_FAIL = "UPGRADE_BY_USER_OBJCECT_FAIL";

export const CREATE_OPINION_BY_USER_OBJCECT_REQUEST = "CREATE_OPINION_BY_USER_OBJCECT_REQUEST";
export const CREATE_OPINION_BY_USER_OBJCECT_SUCCESS = "CREATE_OPINION_BY_USER_OBJCECT_SUCCESS";
export const CREATE_OPINION_BY_USER_OBJCECT_FAIL = "CREATE_OPINION_BY_USER_OBJCECT_FAIL";

export const OPINION_ID_OBJCECT_REQUEST = "OPINION_ID_OBJCECT_REQUEST";
export const OPINION_ID_OBJCECT_SUCCESS = "OPINION_ID_OBJCECT_SUCCESS";
export const OPINION_ID_OBJCECT_FAIL = "OPINION_ID_OBJCECT_FAIL";