export const ADD_RESERVATION_OBJCECT_REQUEST =
  "ADD_RESERVATION_OBJCECT_REQUEST";
export const ADD_RESERVATION_OBJCECT_SUCCESS =
  "ADD_RESERVATION_OBJCECT_SUCCESS";
export const ADD_RESERVATION_OBJCECT_FAIL = "ADD_RESERVATION_OBJCECT_FAIL";

export const DELETE_RESERVATION_OBJCECT_REQUEST =
  "DELETE_RESERVATION_OBJCECT_REQUEST";
export const DELETE_RESERVATION_OBJCECT_SUCCESS =
  "DELETE_RESERVATION_OBJCECT_SUCCESS";
export const DELETE_RESERVATION_OBJCECT_FAIL =
  "DELETE_RESERVATION_OBJCECT_FAIL";

export const GET_USER_RESERVATION_OBJCECT_REQUEST =
  "GET_USER_RESERVATION_OBJCECT_REQUEST";
export const GET_USER_RESERVATION_OBJCECT_SUCCESS =
  "GET_USER_RESERVATION_OBJCECT_SUCCESS";
export const GET_USER_RESERVATION_OBJCECT_FAIL =
  "GET_USER_RESERVATION_OBJCECT_FAIL";

export const UPDATE_RESERVATION_OBJCECT_REQUEST =
  "UPDATE_RESERVATION_OBJCECT_REQUEST";
export const UPDATE_RESERVATION_OBJCECT_SUCCESS =
  "UPDATE_RESERVATION_OBJCECT_SUCCESS";
export const UPDATE_RESERVATION_OBJCECT_FAIL =
  "UPDATE_RESERVATION_OBJCECT_FAIL";

export const GET_BY_ID_RESERVATION_OBJCECT_REQUEST = "GET_BY_ID_RESERVATION_OBJCECT_REQUEST";
export const GET_BY_ID_RESERVATION_OBJCECT_SUCCESS = "GET_BY_ID_RESERVATION_OBJCECT_SUCCESS";
export const GET_BY_ID_RESERVATION_OBJCECT_FAIL = "GET_BY_ID_RESERVATION_OBJCECT_FAIL";
